export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ko">
      <body>
        <header>
          <h1>Next.js로 만드는 블로그~!</h1>
        </header>
        <main>{children}</main>
      </body>
    </html>
  );
}
